Define a constructor for nothrow_t.
If we don't define a constructor clang++ complains:

  kernel/cpprt.cc:13:27: error: default initialization of an object of const type
        'const std::nothrow_t' requires a user-provided default constructor